version: '3.8'
services:
    backend-dev:
        image: "node:18-alpine"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - "8081:37000"
        command: "npm run dev"
        
    db:
        image: "postgres"
        restart: always
        user: "postgres"
        environment:
            - POSTGRES_PASSWORD=example
        ports:
            - "5432:5432"

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080